KMP
dorksan/homeworks pull request #34
Opened 2021-12-14 19:48 UTC by dorksan

2021-12-23 15:33 UTC, yurii-litvinov requested changes

2021-12-23 15:33 UTC, yurii-litvinov commented on projects/homework11/substringSearch/kmp.h
> +void prefixFunction(const char* string, int* prefix, const int sizeOfSubstring, const int sizeOfText);
Префикс-функция извне не нужна, она используется (по идее) только внутри kmp

2021-12-23 15:33 UTC, yurii-litvinov commented on projects/homework11/substringSearch/kmp.c
> +            }
Это можно тернарным оператором

2021-12-23 15:33 UTC, yurii-litvinov commented on projects/homework11/substringSearch/main.c
> +    char* substring = calloc(SIZE_OF_SUBSTRING, sizeof(char));
Если размеры заранее известны, то лучше выделять на стеке. Разве что text всё-таки на куче надо выделять, он большой и компилятор будет ругаться.

2021-12-23 15:33 UTC, yurii-litvinov commented on projects/homework11/substringSearch/kmp.c
> +    char* string = calloc(SIZE + SIZE_OF_SUBSTRING, sizeof(char));
Кажется, её никто не удаляет

2021-12-23 15:33 UTC, yurii-litvinov commented on projects/homework11/substringSearch/main.c
> +            printf("\nПозиция %d-ого вхождения: %d ", i + 1, positionOfEntry[i]);
Кажется, оно пишет не начало вхождения, а конец, а так нехорошо

2021-12-23 20:50 UTC, dorksan commented on projects/homework11/substringSearch/kmp.h
> +void prefixFunction(const char* string, int* prefix, const int sizeOfSubstring, const int sizeOfText);
Ну на нее тест был, но он особо ни на что не влиял, так что удалю

2022-01-07 18:55 UTC, yurii-litvinov commented on projects/homework11/substringSearch/kmp.h
> +void prefixFunction(const char* string, int* prefix, const int sizeOfSubstring, const int sizeOfText);
Ну да, тесты по идее должны проверять видимую функциональность, а не внутренности модуля

2022-01-07 18:58 UTC, yurii-litvinov requested changes

2022-01-07 18:58 UTC, yurii-litvinov commented on projects/homework11/substringSearch/kmp.c
> +        return;
string утечёт

2022-01-07 18:58 UTC, yurii-litvinov commented on projects/homework11/substringSearch/main.c
> +        return -1;
Файл утечёт :)

2022-01-07 18:58 UTC, yurii-litvinov commented on projects/homework11/substringSearch/main.c
> +        return -1;
text утечёт :)

2022-09-18 20:53 UTC, closed without merging