lexer
dorksan/homeworks pull request #37
Opened 2021-12-21 18:30 UTC by dorksan

2021-12-23 14:14 UTC, yurii-litvinov requested changes

2021-12-23 14:14 UTC, yurii-litvinov commented on projects/homework12/lexerOfRealNumbers/lexer.c
> +bool lexer(const char* number)
Методы должны именоваться как глагол в повелительной форме, так что лучше doLexing, analyze или что-то такое

2021-12-23 14:14 UTC, yurii-litvinov commented on projects/homework12/lexerOfRealNumbers/lexer.c
> +    return (symbol >= '0' && symbol <= '9');
```suggestion
    return symbol >= '0' && symbol <= '9';
```

2021-12-23 14:14 UTC, yurii-litvinov commented on projects/homework12/lexerOfRealNumbers/lexer.c
> +            index++;
Это надо делать до switch, автомат читает ровно один символ за переход всегда

2021-12-23 14:14 UTC, yurii-litvinov commented on projects/homework12/lexerOfRealNumbers/lexer.c
> +            state = (isDigit(currentSymbol)) ? DIGIT_ONE : POINT;
Не-а, POINT не обязателен, за первой группой цифр сразу E может быть

2021-12-23 14:14 UTC, yurii-litvinov commented on projects/homework12/lexerOfRealNumbers/main.c
> +    bool isEmail = lexer(realNumber);
Это уже не Email точно :)

2021-12-23 20:00 UTC, dorksan commented on projects/homework12/lexerOfRealNumbers/main.c
> +    bool isEmail = lexer(realNumber);
Забыла переименовать :(((

2022-01-07 18:59 UTC, yurii-litvinov commented on projects/homework12/lexerOfRealNumbers/testLexer.h
> +bool areTestsPassed();
Надо комментарии :)

2022-01-07 18:59 UTC, yurii-litvinov commented on projects/homework12/lexerOfRealNumbers/main.c
> +    bool isEmail = lexer(realNumber);
И так и не переименовали? :)

2022-01-07 19:08 UTC, yurii-litvinov requested changes

2022-01-07 19:08 UTC, yurii-litvinov commented on projects/homework12/lexerOfRealNumbers/lexer.c
> +    int length = strlen(number);
```suggestion
    const int length = strlen(number);
```

2022-01-07 19:08 UTC, yurii-litvinov commented on projects/homework12/lexerOfRealNumbers/lexer.c
> +            state = (isDigit(currentSymbol)) ? DIGIT_ONE : -1;
```suggestion
            state = isDigit(currentSymbol) ? DIGIT_ONE : -1;
```

2022-01-07 19:08 UTC, yurii-litvinov commented on projects/homework12/lexerOfRealNumbers/lexer.c
> +            state = (isDigit(currentSymbol)) ? DIGIT_ONE : POINT;
Тут лучше было уже if-ами или вложенным switch-ем сделать, а то получается, что мы сначала переходим в POINT, а потом тут же в DIGIT_TWO или EXPONENT. А из EXPONENT ещё в SIGN. Можно с ума сойти, разбираясь.

2022-01-07 19:08 UTC, yurii-litvinov commented on projects/homework12/lexerOfRealNumbers/lexer.c
> +                state = (currentSymbol == '.') ? DIGIT_TWO : EXPONENT;
Кстати, не DIGIT_TWO, а "видели точку", потому что так оно примет 1.E+1, что неправильно. Мы должны считать хотя бы одну цифру после точки, так что тут так же, как в начале числа, надо два состояния

2022-01-07 19:08 UTC, yurii-litvinov commented on projects/homework12/lexerOfRealNumbers/lexer.c
> +    char currentSymbol = number[index];
Это чтение за границей массива сразу

2022-01-07 19:08 UTC, yurii-litvinov commented on projects/homework12/lexerOfRealNumbers/lexer.c
> +                state = (currentSymbol == 'E') ? SIGN : -1;
Не-а, знак после E не обязателен. 1E1 является корректным числом

2022-09-18 20:53 UTC, closed without merging