Binary representation
dorksan/homeworks pull request #8
Opened 2021-10-12 20:45 UTC by dorksan

2021-10-14 15:29 UTC, yurii-litvinov requested changes
Всё не так и плохо на самом деле :)

2021-10-14 15:29 UTC, yurii-litvinov commented on projects/homework 4/binary_representation/main.c
> +}
Используйте битовую маску, как на слайдах было. `array[i] = decimalNumber & mask == 0 ? 0 : 1; mask = mask << 1;`. И так от 0 до sizeof(int) * 8 --- чтобы пробежаться по всем битам числа и выложить их в массив

2021-10-14 15:29 UTC, yurii-litvinov commented on projects/homework 4/binary_representation/main.c
> +    int decimalNumber = abs(number);
А прикол в том, что для отрицательных чисел вообще ничего менять не надо, ведь они и так хранятся в дополнительном коде, так что способ с маской будет для них работать и так.

2021-10-14 15:29 UTC, yurii-litvinov commented on projects/homework 4/binary_representation/main.c
> +    for (int i = 0; i < size+1; i++)
```suggestion
    for (int i = 0; i < size + 1; i++)
```

2021-10-14 15:29 UTC, yurii-litvinov commented on projects/homework 4/binary_representation/main.c
> +    }
И при temp равном 0 или 1 в array3 тоже надо что-то положить, но идея такая, да.

2021-10-14 15:29 UTC, yurii-litvinov commented on projects/homework 4/binary_representation/main.c
> +#define SIZE 4
Всякие штуки типа арифметического переполнения (которое тут может быть полезно при переводе обратно) будут правильно работать только если размер числа равен размеру int в битах, так что должно быть вот так:
```suggestion
#define SIZE (sizeof(int) * 8)
```

2021-10-14 15:29 UTC, yurii-litvinov commented on projects/homework 4/binary_representation/main.c
> +    int* arrayFirst = calloc(sizeFirst, sizeof(int));
Можно смело считать, что все массивы имеют размер sizeof(int) * 8, иначе замучаетесь их размеры считать, передавать всюду и проверять каждый раз

2021-10-17 18:46 UTC, yurii-litvinov requested changes

2021-10-17 18:46 UTC, yurii-litvinov commented on projects/homework 4/binary_representation/binaryToDecimal.h
> +int binaryToDecimal(int* array);
Модули --- это средства группировки функций, так что если во всех модулях по одной функции, они ничего не группируют и довольно бесполезны (правда, особо нет разницы, запутаться в сотне функций в одном файле или в сотне файлов). Лучше все функции для работы с двоичным представлением в один модуль сложить.

2021-10-17 18:46 UTC, yurii-litvinov commented on projects/homework 4/binary_representation/binaryAddition.h
> +void binaryAddition(int* array1, int* array2, int* array3);
Никак не догадаться, где слагаемые, а где результат. Переименуйте параметры, пожалуйста

2021-10-17 18:46 UTC, yurii-litvinov commented on projects/homework 4/binary_representation/binaryToDecimal.c
> +#define SIZE 8
Хотелось работать с настоящими int-ами, так что правильнее так:
```suggestion
#define SIZE (sizeof(int) * 8)
```

2021-10-17 18:46 UTC, yurii-litvinov commented on projects/homework 4/binary_representation/binaryToDecimal.c
> +            result = pow(2, SIZE - i - 1) + result;
Не надо двойку в степень каждый раз возводить, лучше завести переменную и умножать её на два на каждой итерации.

2021-10-17 18:46 UTC, yurii-litvinov commented on projects/homework 4/binary_representation/decimalToBinary.c
> +
```suggestion
```

2021-10-17 18:46 UTC, yurii-litvinov commented on projects/homework 4/binary_representation/decimalToBinary.c
> +    int mask = 0b10000000;
Можно было идти с другой стороны, тогда mask был бы сначала просто 1. Иначе Вы замучаетесь 31 ноль писать для настоящих int-ов

2021-10-17 18:46 UTC, yurii-litvinov commented on projects/homework 4/binary_representation/main.c
> +    printf("Введите первое число: ");
Так всё-таки, почему у Вас русские буквы под виндой нормально отображаются? :)

2021-10-17 22:57 UTC, dorksan commented on projects/homework 4/binary_representation/main.c
> +    printf("Введите первое число: ");
Без понятия, я тут точно ни при чем. Наверно такие дефолтные настройки отображения кириллицы

2021-10-31 11:39 UTC, yurii-litvinov approved these changes
Всё правильно, зачтена

2021-10-31 11:39 UTC, yurii-litvinov commented on projects/homework 4/binary_representation/binaryAddition.c
> +        int sum = firstBinaryNumber[i] + secondBinaryNumber[i] + temp;
```suggestion
        const int sum = firstBinaryNumber[i] + secondBinaryNumber[i] + temp;
```

2021-10-31 11:39 UTC, yurii-litvinov commented on projects/homework 4/binary_representation/binaryAddition.h
> +void binaryAddition(int* array1, int* array2, int* array3, int size);
Непонятно, кто слагаемые, а кто результат. Так нельзя именовать аргументы.

2022-09-18 20:53 UTC, closed without merging